version: '3.12' 

services: 
  web: 
    build: . 
    ports: 
      - "8000:8000" 
    depends_on: 
      - db 
    environment: 
      REDIS_HOST: redis 
      KAFKA_BROKERS: kafka:9092 
    networks: 
      - shared_network 
  db: 
    image: postgres:15 
    environment: 
      POSTGRES_PASSWORD: postgres 
    networks: 
      - shared_network 
networks: 
  shared_network: 
    external: true 