# version: '3.8'

# services:
#   kafka:
#     image: wurstmeister/kafka:latest
#     ports:
#       - "9092:9092"
#     environment:
#       KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
#       KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
#       KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
#       KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

#   zookeeper:
#     image: wurstmeister/zookeeper:latest
#     ports:
#       - "2181:2181"

#   postgres:
#     image: postgres:latest
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: postgres
#       POSTGRES_DB: games
#     ports:
#       - "5433:5432"

#   app:
#     build: .
#     ports:
#       - "8000:8000"
#     depends_on:
#       - kafka
#       - postgres
#     environment:
#       KAFKA_BROKERS: kafka:9092
#       KAFKA_TOPIC: search_topic
#       DATABASE_URL: postgres://postgres:postgres@postgres:5432/games


version: '3.8' 

services: 
  web: 
    build: . 
    ports: 
      - "8000:8000" 
    depends_on: 
      - db 
    environment: 
      REDIS_HOST: redis 
      KAFKA_BROKERS: kafka:9092 
    networks: 
      - shared_network 
  db: 
    image: postgres:15 
    environment: 
      POSTGRES_PASSWORD: postgres 
    networks: 
      - shared_network 
networks: 
  shared_network: 
    external: true 